### ISSUE TITLE
routes werken niet bij reload?

### ISSUE THREAD

**Issue by ErnaOudman** [CoderdojoDelft/CoderdojoDelft.github.io#11]
Ik snap niet wat er gebeurd, maar als ik de website open en op de links aan de linkerkant klik, werkt alles.
Maar als ik rechtstreeks naar bijv. https://coderdojo-delft.nl/volgendeeditie ga, krijg ik een 404 error. Dat gebeurt ook bij de andere links.
Kan iemand de routing checken?

**Comment by serra** [comment]
Dit moet severside opgelost worden en volgens mij kan dit niet met gh-pages.

 [voorbeeld]: https://stackoverflow.com/questions/38174410/putting-a-react-router-application-on-github-gh-pages

**Comment by serra** [comment]
Hm, er zijn mensen die dit opgelost hebben.
@joppe kun jij dit eens checken, volgens mij ben jij daar sneller mee dan ik:

https://github.com/rafrex/spa-github-pages

**Comment by serra** [comment]
Useful post: https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48

**Comment by serra** [comment]
A recurring advice is to switch to [hashHistory](https://stackoverflow.com/questions/36289683/what-is-the-difference-between-hashhistory-and-browserhistory-in-react-router)

**Comment by serra** [comment]
Op Heroku krijg ik het aan de praat: :tada:  https://coderdojo-delft.herokuapp.com/volgendeeditie

**Comment by serra** [comment]
Voorstel: switch naar #-navigatie; dan werkt het iig gelijk.

**Comment by joppe** [comment]
https://github.com/CoderdojoDelft/CoderdojoDelft.github.io/pull/16

**Comment by joppe** [comment]
:top: dat is dus de pr die dit probleem oplost met hashes in de url's

**Comment by serra** [comment]
Nu ook gedeployed. @ErnaOudman linkjes werken nu wel. Bijvoorbeeld: 

https://coderdojo-delft.nl/#/mentoren

Cheers!
