### ISSUE TITLE
CNAME deleted when deploying

### ISSUE THREAD

**Issue by ErnaOudman** [CoderdojoDelft/CoderdojoDelft.github.io#6]
First time, CNAME was added directly to master branch. I've made it also in develop branch.
But I guess it should be taken into account when deploying, as it is now not pushed to the master as well.
Re-created CNAME manually now to get the website up again.

O ja, ik ben zo gewend om issues in het Engels te typen, dat ik af en toe vergeet dat het hier ook in NL kan....

**Comment by joppe** [comment]
Daar kwam ik gisteren ook achter...

**Comment by serra** [comment]
@ErnaOudman @joppe @Notalifeform 
Ik heb een automatische build aangemaakt op Travis-CI.
Elke commi op develop wordt nu gepubliceerd naar de live site.
Deze zorgt ervoor dat de CNAME ook goed gezet wordt/blijft.
Bij een handmatige deploy kun je deze fout nog wel maken.
