### ISSUE TITLE
Linkjes werken niet meer

### ISSUE THREAD

**Issue by joppe** [CoderdojoDelft/CoderdojoDelft.github.io#8]
Er zijn een twee linkjes op de "Mentor worden" pagina die niet meer werken sinds we zijn overgegaan naar github. Het gaat om:
- Protocol Veiligheid CoderDojo Nederland
- Vrijwilligers Overeenkomst

Misschien dat de documenten nog in Google Docs staan...

**Comment by serra** [comment]
Fixed with pr #9
